### ISSUE TITLE
`Return` in vi command mode still inserts a line break inside a form

### ISSUE THREAD

**Issue by christoph-frick** [bhauman/rebel-readline#101]
I am aware, that this may or may not be a problem with jline itself, but i just want to get this off my chest.

Right now from a "REPL" perspective it is a bit uncommon (for me) to get a line break (and indenting) from pressing the return key while inside a form.  I am using `:viins`, so exiting to the command mode (ESC) i would expect, that `Return` would execute the current "line" anyway, even if i am inside a form.  But right now this basically starts insert mode again (and inserts a line break first).

**Comment by bhauman** [comment]
This is great feedback... and should be fixed.  I'm not a vi guy so this helps.

**Comment by bhauman** [comment]
It may be hard to fix but thanks for the feedback.

**Comment by christoph-frick** [comment]
I tried some "usualy suspects": Ctrl-m, Ctrl-j, Ctrl-Return.  What does emacs use to send the command off inside a form?

**Comment by christoph-frick** [comment]
For what it's worth: i tried disabling `:repl/toggle-indent` in hope it might just also disable the formatting in general on line break

**Comment by bhauman** [comment]
@trptcolin 
This is an intentional decision. This behavior is what will enable multi-line editing to work along with paredit structural editing. With paredit there are no open forms to tell the line editor that a line break shouldn't submit.

Simple basic paredit is major part of the road map here. So I'm intent on keeping this behavior.

But not in viins. It could be made configurable ... but that will be a separate issue.

**Comment by bhauman** [comment]
This is fixable for sure. I just have to check the mode in the right spot.

**Comment by christoph-frick** [comment]
Another option would be just some sort of "Send the command no matter what".  For vi (or rlwrap in vi mode) there is no key i know off.  But since this might just also be something "uncommon" to the regular rlwrap/repl/sh/... folks, it might be an option to have that on say Ctrl-Return?

**Comment by bhauman** [comment]
@christoph-frick on :vicmd mode I'm just going to turn this ACCEPT_LINE behavior off.

**Comment by bhauman** [comment]
@christoph-frick and @trptcolin 
would love your thoughts on https://github.com/bhauman/rebel-readline/issues/91

**Comment by bhauman** [comment]
fixed and deployed to snapshot

**Comment by trptcolin** [comment]
@bhauman :+1: I understand the use case and decision, and it’s an easy enough workaround (end of line first). But so far I don’t see why they should be different for vi & emacs for this use case - e.g. Vim has a good paredit that I use. Is the idea that there will be paredit for emacs mode only?

**Comment by trptcolin** [comment]
:facepalm: ignore me, sorry, I didn’t read apparently, what you changed (vicmd) totally makes sense.

**Comment by christoph-frick** [comment]
Tried it.  Works fine.  Thank you.

**Comment by bkovitz** [comment]
Apparently, `:vicmd` mode starts each new line in command mode rather than insert mode. That makes the REPL a lot less convenient.

How hard would it be to make `:viins` mode work like this?

1. The Return key accepts the line, no matter what.

2. While in insert mode, Shift-Return inserts a newline without accepting the line.

This is a pretty common convention, and it does the most convenient thing (at least for vi users) nearly all the time, as well as being expected (at least by vi users).

**Comment by christoph-frick** [comment]
I suggested that a while ago and now after using the current mode a bit i really would like to see that working that way (return sends, no matter what) or provide an option to make it work that way. The problem with the current way is also intensified by the fact, that ctrl-w after a new line not only removes the line break but also the last word.

**Comment by bhauman** [comment]
I'm certainly willing to take another look at this.  It might be a little while.

But let's keep all the variables in mind. 
Currently in :vicmd hitting enter submits no matter what.
Currently in :viins hitting enter submits *if* you are not inside a form (complete or incomplete). Otherwise it line-breaks and indents.  In emacs mode this is done to support paredit mode.

It sounds like you are not wanting the Readline to detect if you have an incomplete form in `:viins` at all when you hit enter. And that you want to manually create newlines with Shift-Enter. 

Unfortunately, I have to trust what you are asking for as I'm not a Vi user.  And I will need some assurance that this will really work for people. 

It seems odd to my sensibilities that when folks are in an "incomplete" form, they will want enter to submit the form anyway.

It may be that what we actually want here is for enter to submit a form when only it is complete?
 
cc/ @trptcolin 

Just want to make sure that we are defining the behavior correctly. As we need to settle on behavior that solves the need universally in the best way for everyone.

Also, we need to keep in mind that I'm going to have a plugin architecture where you can define behavior for these things.  Although, line acceptance is a bit tricky in Jline currently.

Also, I am going to define a force line accept command that will bypass all these things.

**Comment by trptcolin** [comment]
For my use case, the "force line accept command that will bypass all these things" is totally awesome and works great for me. And just so I'm sure I'm disambiguating "line" properly, given multi-line scenario, I'm assuming in the context of a multi-line expression that you've jumped back up to the top to edit, this would allow you to accept the full multi-line input.

It's tough to think about what the key combo should be because the "force line accept" vs. "suppress line accept" seems to be a different key combo across every GUI app I use, but I'm sure I could get used to whatever's available!  But I've been doing some python, using ipython for a REPL, and have noticed and been mildly annoyed by the not-accepting-full-command, but didn't bother trying to figure it out now - for what it's worth, on MacOS, ipython uses Option-Enter for this use case.

**Comment by christoph-frick** [comment]
So i tried 0.1.1 right now (basically followed the instructions from the README).  I added the `:viins` as described in the README.  So what happes right now is this:

- start the repl
- we are in insert mode, and i can type
- enter `(+ 1 2 3)<CR>` works fine
- next line i press `<ESC>k` to move up in history
- move cursor before `2`, `i4`.  line looks like `(+ 1 4|2 3)` -- `|` is the cursor
- now i press `<CR>` - rebel-rl now breaks the line, it looks like this:

```
(+ 1 4
   2 3)
```
pressing `<ESC><CR>` works.

So i am not sure, when you say "incomplete form", if you mean "incomplete at the cursor position" or if that is actually a bug, which does not detect, that the form is in itself complete.

**Comment by bhauman** [comment]
@christoph-frick yes that is how it works now, I'm referring to possibly new behavior for :viins where it may be desirable for an incomplete form to not be submitted on enter.  The current behavior is the behavior that we want in emacs mode where paredit will be king soon enough and every form will be a complete form.

@trptcolin yes the force-accept would accept the full multiline edit. Yeah the ultimate binding for that might be tough to settle on ...

I also want to clarify that we need to be aware not to let habits from gained from using REPLs that didn't have multiline editing or exacted a heavy price when you didn't have a complete form, or would accept partial lines which one no longer could access, guide this new experience which is much more editor like. We should be guided more by what happens in a vi edit buffer where I'm sure that enter creates a new line and indents.

**Comment by bkovitz** [comment]
bhauman: I hear you on not letting old habits dictate the design of rebel-readline when those habits would fail to make good use of the new features that rebel-readline offers. It might help, then, if I explain the common situation where I (and I think many vi users) want Return to accept the line even if the cursor is inside an incomplete form in insert mode.

1. I type `(clojure.string/split "this is some stuff" #" ")`. (I did this yesterday when I couldn't remember how to split a string into words.)<br>`["this" "is" "some" "stuff"]`

2. Now I want to see if `#" "` splits correctly when there are multiple spaces in a row. I hit Esc K (or up-arrow), move the cursor into the string in insert mode and type a few spaces, so it looks like this:<br>`(clojure.string/split "this is some    stuff" #" ")`<br>Now I hit Return, wanting to see the result.

This sort of thing happens a lot, at least for me and other people I know. I just want to make a small change to a previous line and run it. Currently, when I hit Return, the line breaks and have to repair it.

What would be a convenient way to do this, that doesn't clash with the flow of rebel-readline?

**Comment by christoph-frick** [comment]
From an editor-buffer viewpoint, return does nothing except insert a line or goes to the next line in cmd-mode.  So by that metaphor i'd even say, i want to be able to configure a key (or learn one), that does the "execute".  When i code clojure with fireplace i dont have to go to the end of the form and press enter to execute it.  i press a shortcut to execute the current form or the outermost form or the whole buffer.

I guess this is clearly my problem here.  I love rebel-rl for all the things it adds to the repl.  The vi-mode (which is jline) is not totally terrible.  So for as far a repls etc go, i only ever use them to enter single lines most of the time.  As soon as things get elaborate i switch to an editor and use load-file or tslime or direct integration.

So instead of finding ways to please all crowds and make viins/vimd even more special snowflakes, what about going the other way around: add a config switch to just disable multi line editing at all (default off).

**Comment by bkovitz** [comment]
Say, in emacs, are you always in "insert mode"? That might explain the disconnect with vi's prehistoric use of insert mode and command mode (in violation of all contemporary UI accumulated wisdom, but it works wonderfully in practice). If you were always in insert mode, using the cursor keys to move around, then I can see how you would expect Return to break a line at the cursor.

Editing in vi has a different "rhythm". Command mode is your "home", your "ready" position. You only move the cursor around in command mode. When you want to make a change, you do some command that puts you temporarily into insert mode, and as soon as you're done, you hit Esc so you're back in command mode. If you were to walk away from the computer and come back, you would expect that the editor would be in command mode, because that's what it's normally in.

(vim lets you move the cursor while in insert mode, but that's a compromise for people who never master the editor. It runs against the natural flow, because it undermines useful stuff like the dot command and 'movements' as arguments to commands. It only makes sense to "repeat the last edit where the cursor is now" if editing consists of a sequence of small edits done at different locations.)

When you want to add a new line to the file you're editing, you put the cursor on an existing line and hit `o` or `O` to "open" a new line below or above it—not by hitting Return. In command mode, Return means "move the cursor to the next line". (The `o` and `O` commands also put you into insert mode, of course.) You do break an existing line apart by hitting Return while in insert mode, but this a fairly uncommon operation. 

When operating programs that have readline with vi-mode, it feels natural that Return should mean "I'm done". The vi rhythm is basically "type a little text, I'm done (with that edit); type a little text, I'm done; type a little text, I'm done."

Shift-Return feels like a "special" variant of Return. And breaking a line into a multi-line command in the REPL feels like a "special" sort of edit. So this might be the best fit for vi users to split a command line into two lines.

**Comment by bhauman** [comment]
So here is my take away from this:

I'm going to allow the disabling of multi-line editing with an `:always-accept-on-enter` config.
It will default to false.

I will make it so that there is a `force-accept` widget that will be bound to `Ctrl-M`(carriage return)  for emacs mode. I will need some input for the best bindings for `:viins` and `:vicmd`.

I'm considering having open forms not accept in `:viins` by default instead of the current behavior.

**Comment by christoph-frick** [comment]
I think ctrl-j or ctrl-m like in emacs are fine.  So if i understood that correctly:
- there will a default-off-toggle to disable multi line edit; so a return anywhere in a line will just send the line off
- to get multi line editing in this mode, one can press ctlr-m, like in a regular vi and emacs session

So no more special cases for vi, all work the same.  And if you invert the keys with this toggle, even users that dont have it on, could use cltr-lm to send the line off anywhere.

Sounds good to me

**Comment by bhauman** [comment]
Not quite what I was trying to say.

The default experience will be what it is now, Enter breaks/indents if its in the middle of a form.  This is what the vi editor does.

You can turn this off with a config option and/or :repl/comand so that Enter sends regardless.

Ctrl-M will send the line buffer for eval no matter what.
If you want a binding for break/indent I can do that as well.

**Comment by bhauman** [comment]
This is of course harder than I thought it would be, its extremely tricky to get a good binding to work for this.   Getting the keybinding for "shift return" and many other "enter" key combos is proving very difficult in Jline.  And messing with Ctrl-J and Ctrl-M is just asking for trouble as fas as platform support is still ambiguous regarding what is sent when.

So for now I have added a ctrl-E to :viins mode for "eval" as is.

I've spent 3 hours on this trying to find a good balance for these needs and figure out the right key bindings.

Also turning off multi-line editing is not the right solution.

The only real solution here is configurable key bindings, and plugins.

**Comment by bhauman** [comment]
I just added key-binding configuration.

In the config file you can now customize this behavior as you wish: 

```
:key-bindings {:viins [["^M" :clojure-force-accept-line
                                      "^J"  :clojure-force-accept-line]]}
```

Where "^M" will normally override you the return key.

**Comment by christoph-frick** [comment]
I tried 0.1.2 and that works very well for me.  Out of reflex i see myself pressing enter at first, but once you are in the groove this is great.  Thank you!

**Comment by bkovitz** [comment]
I just tried out `[com.bhauman/rebel-readline "0.1.2"]`. It works. I can hit Return to execute the line even while in Insert mode *and* I can hit Ctrl-J to insert a line break to edit a multi-line command. Thanks!

For anyone reading and wanting to set this up, here's what to put in `~/.clojure/rebel-readline.edn`:
```
{:key-map :viins
 :key-bindings {:viins [["^M" :clojure-force-accept-line
                         "^J" :clojure-force-accept-line]]}}
```
I don't understand why setting `^J` to `:clojure-force-accept-line` makes Ctrl-J insert a line-break when in Insert mode (that sounds backward), but this does work.

----
I'd still prefer that Shift-Return insert a line break as it does in most user interfaces where Return means some form of "accept", but Shift-Return lacks an ASCII code, and I understand that this might not be feasible anytime soon. Much gratitude for slogging through the nuisance required to discriminate between `^J` and `^M`.

And thanks for determining that disabling multi-line editing is not the solution. Non-trivial actions are crippled in the standard REPL because of the lack of multi-line editing. I look forward to learning to make much better use of the REPL now that editing a multi-line command is easy and intuitive—even for us *vi* users.

**Comment by metametadata** [comment]
@bkovitz thank you for an example. But there's a typo: it should be `~/.clojure/rebel_readline.edn` instead of `~/.clojure/rebel-readline.edn`.

This also works in case one wants no multiline editing and click Enter to accept:

    {:key-bindings {:emacs [[(13) :clojure-force-accept-line]]}}

Not sure then how to insert newlines though.
