### ISSUE TITLE
a default configuration edn filename and location "rebel-readline.edn" ?

### ISSUE THREAD

**Issue by bhauman** [bhauman/rebel-readline#91]
It would be nice to have an accepted default for a configuration file even if rebel-readline doesn't read configuration by default (seperate decision). But the repls created from rebel-readline would all benefit from this convention.

And should it be in the users .dot-files?

I'm not experienced enough to make a good decision here and I'm looking for some advice/discussion on this matter.

**Comment by bhauman** [comment]
~/.clj-rebel-readline.edn

maybe this would be overriden with a local clj-rebel-readline.edn

I'm adding the `clj-` as a way method of scoping this to clojure.

Perhaps content like
`{:rebel-readline/config {:key-map :viins}}`
This would allow plugins to piggieback on on this config file, 
`{:rebel-readline/config {:key-map :viins}
   :rebel-readline-paredit/config {...}}`

**Comment by christoph-frick** [comment]
While i currently use rebel-rl inside something that already allows for reading
the config, i'd guess it would make sense to allow for a config.  Maybe a goal
to go for could actually be `rlwrap` here (or readline in general).  It allows
me to provide an `~/.inputrc` OR an `$INPUTRC` so i have a pretty consistent
way to tell many things (e.g. `rlwrap`, `psql`, ...) "i just want vi mappings,
and i want this and that".  So tools utilizing rebel-rl, give me the same
setup.

With `rlwrap` i use further command line switches (packed in an alias), but i
guess this is not really an option, since rebel-rl is most likely already
contained into whatever starts it.

So from a Unix perspective, environment and `~/.dotfile` are IMHO things to aim
for.  And `-D...` options for Java are doable.  What's a good pattern for CLJS
and e.g. Lumo i can't tell.

Assuming, that CLJ and CLJS and ... related rebel-rl might share alot (but not
all?) config switches, i'd probably would prefer a way to keep a central
config, that gives me the "all my settings are used"-experience for all of them
and then override where needed (imagine profiles in Leinigen) e.g. one file in
the ilk of:

```clojure
{:key-map :viins
 :cljs/key-map :emacs}
```

**Comment by jwhitlark** [comment]
If there's any chance of having more than one file, I'd suggest a dot directory at ~/ instead of a file.

**Comment by trptcolin** [comment]
User-level dotfiles makes sense to me as an option. I can imagine consuming tools (e.g. lein/boot) preferring to pass a map in so their users can avoid adding more config files. But yeah as long as that capability exists, a dotfiles location like the one you suggest makes sense to me.
